import { prisma } from "@/lib/prisma";

const unavailable: Record<string, string> = { payments: "Payment data is not configured. Connect a payment data source to enable this section.", subscriptions: "Subscription data is not configured. Connect a subscription data source to enable this section.", certificates: "Certificate data is not configured.", notifications: "Notifications are not configured yet.", settings: "No admin settings are stored in the current schema." };

export async function AdminDataPage({ kind }: { kind: "courses" | "assignments" | "exams" | "timetable" | "study-plans" | "copilot" | "reports" | "ai-usage" | "analytics" | "payments" | "subscriptions" | "certificates" | "notifications" | "settings" }) {
  const title = kind.replace("study-plans", "study plans").replace("ai-usage", "AI usage").replace("copilot", "AI Copilot").replace("-", " ");
  if (unavailable[kind]) return <section className="p-6 lg:p-8"><p className="text-sm font-medium text-primary">Management</p><h1 className="mt-1 text-3xl font-semibold capitalize tracking-tight">{title}</h1><div className="mt-8 max-w-xl rounded-xl border border-dashed border-slate-300 bg-white p-8 dark:border-slate-700 dark:bg-slate-900"><h2 className="font-semibold">Data source not configured</h2><p className="mt-2 text-sm text-slate-500">{unavailable[kind]}</p></div></section>;
  const result = kind === "courses" ? await prisma.course.findMany({ select: { id: true, courseName: true, courseCode: true, instructor: true, semester: true, createdAt: true, user: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 100 }) : kind === "assignments" ? await prisma.assignment.findMany({ select: { id: true, title: true, deadline: true, status: true, user: { select: { name: true } }, course: { select: { courseName: true } } }, orderBy: { deadline: "asc" }, take: 100 }) : kind === "exams" ? await prisma.exam.findMany({ select: { id: true, examType: true, date: true, user: { select: { name: true } }, course: { select: { courseName: true } } }, orderBy: { date: "asc" }, take: 100 }) : kind === "timetable" ? await prisma.timetable.findMany({ select: { id: true, subjectName: true, date: true, startTime: true, endTime: true, status: true, user: { select: { name: true } } }, orderBy: { date: "asc" }, take: 100 }) : kind === "study-plans" ? await prisma.studyPlan.findMany({ select: { id: true, generatedAt: true, user: { select: { name: true, email: true } } }, orderBy: { generatedAt: "desc" }, take: 100 }) : await prisma.copilotMessage.findMany({ select: { id: true, role: true, content: true, createdAt: true, conversation: { select: { user: { select: { name: true, email: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 });
  const date = new Intl.DateTimeFormat("en", { dateStyle: "medium" });
  const rows = result.map((item) => { const record = item as Record<string, unknown>; const user = record.user as { name: string } | undefined; const course = record.course as { courseName: string } | undefined; const conversation = record.conversation as { user: { name: string; email: string } } | undefined; return { id: String(record.id), primary: String(record.title || record.courseName || record.examType || record.subjectName || (conversation ? `${conversation.user.name}: ${record.role}` : user?.name || "Record")), secondary: course?.courseName || user?.name || (conversation?.user.email ?? ""), status: String(record.status || record.role || ""), date: record.deadline || record.date || record.generatedAt || record.createdAt }; });
  return <section className="p-6 lg:p-8"><div className="mb-8"><p className="text-sm font-medium text-primary">Academic management</p><h1 className="mt-1 text-3xl font-semibold capitalize tracking-tight">{title}</h1><p className="mt-2 text-sm text-slate-500">{rows.length} records loaded from the current database.</p></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{rows.length === 0 ? <p className="p-6 text-sm text-slate-500">No {title} available.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th className="px-5 py-3">Record</th><th className="px-5 py-3">Student / course</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map(row => <tr key={row.id}><td className="px-5 py-4 font-medium">{row.primary}</td><td className="px-5 py-4 text-slate-500">{row.secondary}</td><td className="px-5 py-4 text-slate-500">{row.status || "Not available"}</td><td className="px-5 py-4 text-slate-500">{row.date ? date.format(new Date(String(row.date))) : "Not available"}</td></tr>)}</tbody></table></div>}</div></section>;
}
