import Link from "next/link";
import { Activity, Award, BookOpen, Brain, CalendarClock, ClipboardList, Users } from "lucide-react";
import { getAdminMetrics, formatDate } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

export default async function AdminPage() {
    const metrics = await getAdminMetrics();
    const [recentUsers, upcomingExams] = await Promise.all([
        prisma.user.findMany({ where: { role: "STUDENT" }, select: { id: true, name: true, email: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 5 }),
        prisma.exam.findMany({ select: { id: true, examType: true, date: true, course: { select: { courseName: true } } }, orderBy: { date: "asc" }, take: 5 }),
    ]);
    const cards = [["Students", metrics.students, Users], ["Active, 30 days", metrics.activeStudents, Activity], ["New, 30 days", metrics.newStudents, Users], ["Courses", metrics.courses, BookOpen], ["Assignments", metrics.assignments, ClipboardList], ["Exams", metrics.exams, CalendarClock], ["AI messages", metrics.aiUsage, Brain]] as const;
    return <section className="p-6 lg:p-8"><div className="mb-8"><p className="text-sm font-medium text-primary">Overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Admin dashboard</h1><p className="mt-2 text-sm text-slate-500">A live view of your university workspace.</p><div className="mt-4"><Link href="/admin/organizations" className="inline-flex rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Review organization registrations</Link></div></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="text-2xl font-semibold">{value ?? "Not configured"}</p></div>)}</div>
        <div className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Recent students</h2><Link href="/admin/users" className="text-sm text-primary">View all</Link></div>{recentUsers.length === 0 ? <p className="p-5 text-sm text-slate-500">No students found.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{recentUsers.map(user => <div key={user.id} className="flex items-center justify-between px-5 py-4"><div><p className="text-sm font-medium">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></div><time className="text-xs text-slate-500">{formatDate(user.createdAt)}</time></div>)}</div>}</div>
            <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Upcoming exams</h2><Link href="/admin/exams" className="text-sm text-primary">View all</Link></div>{upcomingExams.length === 0 ? <p className="p-5 text-sm text-slate-500">No exams found.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{upcomingExams.map(exam => <div key={exam.id} className="flex items-center justify-between px-5 py-4"><div><p className="text-sm font-medium">{exam.examType}</p><p className="text-xs text-slate-500">{exam.course.courseName}</p></div><time className="text-xs text-slate-500">{formatDate(exam.date)}</time></div>)}</div>}</div></div>
        <div className="mt-8 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Award className="h-5 w-5 text-slate-400" /><div><h2 className="font-semibold">Certificates and revenue</h2><p className="mt-1 text-sm text-slate-500">No certificate, subscription, payment, or revenue tables exist in the current Prisma schema. These metrics are intentionally not fabricated.</p></div></div></div>
    </section>;
}
