import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { Activity, BarChart3, BookOpen, Brain, CalendarClock, ClipboardList, Users } from "lucide-react";

export default async function AdminPage() {
    const [students, activeStudents, courses, assignments, exams, studyPlans, aiUsage, recentUsers, recentAssignments] = await Promise.all([
        prisma.user.count({ where: { role: "STUDENT" } }),
        prisma.user.count({ where: { role: "STUDENT", updatedAt: { gte: new Date(Date.now() - 30 * 86400000) } } }),
        prisma.course.count(),
        prisma.assignment.count(),
        prisma.exam.count(),
        prisma.studyPlan.count(),
        prisma.copilotMessage.count(),
        prisma.user.findMany({ where: { role: "STUDENT" }, select: { id: true, name: true, email: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 5 }),
        prisma.assignment.findMany({ select: { id: true, title: true, status: true, deadline: true, user: { select: { name: true } }, course: { select: { courseName: true } } }, orderBy: { deadline: "asc" }, take: 5 }),
    ]);
    const cards = [["Total students", students, Users], ["Active students", activeStudents, Activity], ["Courses", courses, BookOpen], ["Assignments", assignments, ClipboardList], ["Exams", exams, CalendarClock], ["Study plans", studyPlans, Brain], ["AI Copilot usage", aiUsage, BarChart3]] as const;
    const date = new Intl.DateTimeFormat("en", { dateStyle: "medium" });
    return <section className="p-6 lg:p-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">University Overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Monitor your university</h1><p className="mt-2 text-sm text-slate-500">Students, academics, activity and performance from live database records.</p></div><time className="text-sm text-slate-500">{date.format(new Date())}</time></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon]) => <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" key={label}><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="mt-4 text-3xl font-semibold">{value}</p></div>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Recent students</h2><Link href="/admin/users" className="text-sm text-primary">View all</Link></div>{recentUsers.length === 0 ? <p className="p-5 text-sm text-slate-500">No students found.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{recentUsers.map(user => <div className="flex items-center justify-between px-5 py-4" key={user.id}><div><p className="text-sm font-medium">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></div><time className="text-xs text-slate-500">{date.format(user.createdAt)}</time></div>)}</div>}</div><div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Upcoming assignments</h2><Link href="/admin/assignments" className="text-sm text-primary">View all</Link></div>{recentAssignments.length === 0 ? <p className="p-5 text-sm text-slate-500">No assignments available.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{recentAssignments.map(item => <div className="flex items-center justify-between gap-4 px-5 py-4" key={item.id}><div><p className="text-sm font-medium">{item.title}</p><p className="text-xs text-slate-500">{item.user.name} · {item.course.courseName}</p></div><span className="text-xs text-slate-500">{item.status}</span></div>)}</div>}</div></div></section>;
}