import Link from "next/link";
import { Activity, ArrowUpRight, Bell, BookOpen, Brain, CalendarClock, ClipboardList, FileText, GraduationCap, Users } from "lucide-react";
import { getAdminMetrics, formatDate } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { AdminNotificationComposer } from "@/components/admin/admin-notification-composer";

export default async function AdminPage() {
    const metrics = await getAdminMetrics();
    const [recentUsers, upcomingExams] = await Promise.all([
        prisma.user.findMany({ where: { role: { not: "ADMIN" } }, select: { id: true, name: true, email: true, image: true, role: true, university: true, department: true, createdAt: true, _count: { select: { courses: true, assignments: true, exams: true, notifications: true } } }, orderBy: { createdAt: "desc" }, take: 8 }),
        prisma.exam.findMany({ select: { id: true, examType: true, date: true, course: { select: { courseName: true } } }, orderBy: { date: "asc" }, take: 5 }),
    ]);
    const cards = [
        ["Students", metrics.students, Users, "bg-blue-50 text-blue-600"],
        ["Active this month", metrics.activeStudents, Activity, "bg-emerald-50 text-emerald-600"],
        ["Organizations", metrics.organizations, GraduationCap, "bg-violet-50 text-violet-600"],
        ["Notifications", metrics.notifications, Bell, "bg-amber-50 text-amber-600"],
    ] as const;
    const recordCards = [["Courses", metrics.courses, BookOpen], ["Assignments", metrics.assignments, ClipboardList], ["Exams", metrics.exams, CalendarClock], ["Study materials", metrics.studyMaterials, FileText], ["AI messages", metrics.aiUsage, Brain]] as const;
    return <section className="space-y-6 p-6 lg:p-8">
        <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium uppercase tracking-[0.12em] text-primary">Workspace overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Admin dashboard</h1><p className="mt-2 text-sm text-slate-500">Monitor every part of your university workspace from one place.</p></div><Link href="/admin/organizations" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white transition hover:opacity-90">Review organizations <ArrowUpRight className="h-4 w-4" /></Link></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="mb-5 flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${color}`}><Icon className="h-4 w-4" /></span></div><p className="text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">Live database count</p></div>)}</div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{recordCards.map(([label, value, Icon]) => <Link href={`/admin/${label === "Study materials" ? "reports" : label.toLowerCase()}`} key={label} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 transition hover:border-primary/40 dark:border-slate-800 dark:bg-slate-900"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><Icon className="h-4 w-4" /></span><span><span className="block text-lg font-semibold">{value}</span><span className="block text-xs text-slate-500">{label}</span></span></Link>)}</div>
        <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div><h2 className="font-semibold">Users and activity</h2><p className="mt-1 text-xs text-slate-500">Recent students and organizations</p></div><Link href="/admin/users" className="text-sm font-medium text-primary">View all</Link></div>{recentUsers.length === 0 ? <p className="p-5 text-sm text-slate-500">No users found.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{recentUsers.map(user => <div key={user.id} className="flex items-center gap-3 px-5 py-3.5"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-sm font-semibold text-primary">{user.image ? <img src={user.image} alt="" className="h-full w-full object-cover" /> : user.name.slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user.name}</p><p className="truncate text-xs text-slate-500">{user.email}</p><p className="mt-1 truncate text-[11px] text-slate-400">{user.role === "ORGANIZATION" ? "Organization" : `${user.university || "University not set"} · ${user.department || "Department not set"}`}</p></div><div className="hidden text-right text-[11px] text-slate-400 sm:block"><p>{user._count.courses} courses</p><p>{user._count.assignments} assignments</p><p>{formatDate(user.createdAt)}</p></div></div>)}</div>}</div>
            <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div><h2 className="font-semibold">Upcoming exams</h2><p className="mt-1 text-xs text-slate-500">Across all student accounts</p></div><Link href="/admin/exams" className="text-sm font-medium text-primary">View all</Link></div>{upcomingExams.length === 0 ? <p className="p-5 text-sm text-slate-500">No exams found.</p> : <div className="divide-y divide-slate-100 dark:divide-slate-800">{upcomingExams.map(exam => <div key={exam.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-medium">{exam.examType}</p><p className="text-xs text-slate-500">{exam.course.courseName}</p></div><time className="shrink-0 rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">{formatDate(exam.date)}</time></div>)}</div>}</div></div>
        <AdminNotificationComposer />
    </section>;
}
