"use client";

import { useEffect, useState } from "react";
import { CalendarDays, Clock3, RotateCcw, Volume2 } from "lucide-react";
import type { CopilotResponse } from "@/lib/copilot";
import { AITextResponse } from "./ai-text-response";

const priorityClass = { HIGH: "text-danger", MEDIUM: "text-warning", LOW: "text-success" };
const priorityBadge = { HIGH: "bg-danger/10 text-danger", MEDIUM: "bg-warning/10 text-warning", LOW: "bg-success/10 text-success" };

type ReadAloud = (text: string) => void;

function FocusSession({ response }: { response: Extract<CopilotResponse, { type: "focus_session" }> }) {
    const [remaining, setRemaining] = useState(response.duration * 60);
    const [running, setRunning] = useState(false);
    useEffect(() => { if (!running || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [running, remaining]);
    return <div className="mt-3 rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{response.subject}</p><p className="text-small text-slate-500 dark:text-slate-400">{response.topic}</p></div><Clock3 className="h-5 w-5 text-primary" /></div><p className="my-4 text-center text-3xl font-semibold tabular-nums text-primary">{Math.floor(remaining / 60).toString().padStart(2, "0")}:{(remaining % 60).toString().padStart(2, "0")}</p><div className="flex gap-2"><button type="button" onClick={() => setRunning((value) => !value)} className="rounded-lg bg-primary px-3 py-2 text-small font-medium text-white">{remaining === 0 ? "Completed" : running ? "Pause" : "Start Session"}</button><button type="button" onClick={() => { setRemaining(response.duration * 60); setRunning(false); }} aria-label="Reset focus session" title="Reset focus session" className="rounded-lg border border-slate-200 p-2 dark:border-slate-700"><RotateCcw className="h-4 w-4" /></button></div></div>;
}

function Quiz({ response }: { response: Extract<CopilotResponse, { type: "quiz" }> }) {
    const [answers, setAnswers] = useState<Record<number, string>>({});
    const score = response.questions.reduce((total, question, index) => total + (answers[index] === question.answer ? 1 : 0), 0);
    return <section className="mt-3 space-y-3"><h4 className="font-semibold">AI Quiz</h4>{response.questions.map((question, index) => <div key={`${question.question}-${index}`} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><p className="font-medium">Question {index + 1} of {response.questions.length}: {question.question}</p><div className="mt-3 grid gap-2">{question.options.map((option) => <button key={option} type="button" onClick={() => setAnswers((current) => ({ ...current, [index]: option }))} className={`rounded-lg border p-2 text-left text-small ${answers[index] === option ? option === question.answer ? "border-success bg-success/10" : "border-danger bg-danger/10" : "border-slate-200 dark:border-slate-700"}`}>{option}</button>)}</div>{answers[index] && <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{question.explanation}</p>}</div>)}{response.questions.length > 0 && <p className="text-small font-medium text-primary">Score: {score}/{response.questions.length}</p>}</section>;
}

function Flashcards({ response }: { response: Extract<CopilotResponse, { type: "flashcards" }> }) {
    const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const card = response.cards[index]; if (!card) return null;
    return <section className="mt-3 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h4 className="mb-3 font-semibold">AI Flashcards</h4><button type="button" onClick={() => setFlipped((value) => !value)} className="min-h-28 w-full rounded-lg bg-slate-100 p-5 text-center dark:bg-slate-800"><p className="text-xs font-medium uppercase text-primary">{flipped ? "Answer" : "Question"}</p><p className="mt-2 font-medium">{flipped ? card.answer : card.question}</p></button><div className="mt-3 flex items-center justify-between text-small text-slate-500"><button type="button" disabled={index === 0} onClick={() => { setIndex((value) => value - 1); setFlipped(false); }} className="disabled:opacity-40">Previous</button><span>{index + 1} / {response.cards.length}</span><button type="button" disabled={index === response.cards.length - 1} onClick={() => { setIndex((value) => value + 1); setFlipped(false); }} className="disabled:opacity-40">Next</button></div></section>;
}

function StudyPlan({ response }: { response: Extract<CopilotResponse, { type: "study_plan" }> }) {
    const { summary, sessions } = response;
    return <div className="mt-4 space-y-5"><section><h4 className="mb-3 font-semibold">Study Snapshot</h4><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Study hours", `${summary.totalStudyHours}h`], ["Subjects", summary.subjects.length], ["Priority topics", summary.highPriorityTopics.length], ["Revision sessions", summary.revisionSessions]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-100 p-3 dark:bg-slate-800"><strong className="block text-lg text-primary">{value}</strong><span className="text-xs text-slate-500">{label}</span></div>)}</div></section>{summary.highPriorityTopics.length > 0 && <section><h4 className="mb-3 font-semibold">Priority Topics</h4><div className="flex flex-wrap gap-2">{summary.highPriorityTopics.map((topic) => <span key={topic} className="rounded-full bg-danger/10 px-3 py-1 text-xs font-medium text-danger">HIGH | {topic}</span>)}</div></section>}<section><h4 className="mb-3 font-semibold">Today&apos;s Schedule</h4><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700"><table className="min-w-[650px] w-full text-left text-small"><thead className="bg-slate-100 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="sticky left-0 px-3 py-3">Time</th><th className="px-3 py-3">Subject</th><th className="px-3 py-3">Topic</th><th className="px-3 py-3">Activity</th><th className="px-3 py-3">Priority</th></tr></thead><tbody>{sessions.map((session) => <tr key={`${session.time}-${session.subject}`} className="border-t border-slate-200 transition hover:bg-primary/5 dark:border-slate-700"><td className="sticky left-0 bg-white px-3 py-3 font-medium text-primary dark:bg-slate-900">{session.time}</td><td className="px-3 py-3 font-medium">{session.subject}</td><td className="px-3 py-3 text-slate-600 dark:text-slate-300">{session.topic}</td><td className="px-3 py-3 text-slate-500">{session.duration} min | {session.studyType}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-medium ${priorityBadge[session.priority]}`}>{session.priority}</span></td></tr>)}</tbody></table></div></section><section className="rounded-xl border border-primary/20 bg-primary/5 p-4"><h4 className="font-semibold">Recommended Next Step</h4><p className="mt-1 text-small">Start with {sessions[0]?.subject ?? summary.subjects[0] ?? "your highest-priority topic"}{sessions[0]?.topic ? ` - ${sessions[0].topic}` : ""} for a focused {sessions[0]?.duration ?? 45}-minute block.</p></section></div>;
}

function WeeklyTimetable({ response }: { response: Extract<CopilotResponse, { type: "weekly_timetable" }> }) { return <div className="mt-3 overflow-x-auto"><div className="min-w-[620px] space-y-2">{response.sessions.map((session) => <div key={`${session.day}-${session.time}-${session.subject}`} className="grid grid-cols-[90px_90px_1fr_70px] gap-2 rounded-lg border border-slate-200 p-3 text-small dark:border-slate-700"><span className="flex items-center gap-1 text-primary"><CalendarDays className="h-3.5 w-3.5" />{session.day}</span><span>{session.time}</span><span><strong>{session.subject}</strong><br /><span className="text-xs text-slate-500">{session.topic} | {session.studyType}</span></span><span className={priorityClass[session.priority]}>{session.duration}m</span></div>)}</div></div>; }

export function StructuredResponse({ response, onReadAloud }: { response: CopilotResponse; onReadAloud?: ReadAloud }) {
    const content = response.type === "text" ? <AITextResponse response={response} /> : response.type === "study_plan" ? <StudyPlan response={response} /> : response.type === "weekly_timetable" ? <WeeklyTimetable response={response} /> : response.type === "quiz" ? <Quiz response={response} /> : response.type === "flashcards" ? <Flashcards response={response} /> : response.type === "focus_session" ? <FocusSession response={response} /> : <div className="rounded-lg bg-warning/10 p-3 text-small">{response.message}</div>;
    return <div className="space-y-2">{response.title && <h3 className="font-semibold">{response.title}</h3>}{response.type !== "text" && <p>{response.message}</p>}{content}{onReadAloud && <button type="button" onClick={() => onReadAloud(response.message)} className="mt-2 flex items-center gap-1 text-xs text-primary"><Volume2 className="h-3.5 w-3.5" /> Read aloud</button>}</div>;
}
