"use client";

import { FileText, WandSparkles } from "lucide-react";

export type WorkspaceMode = "Communication" | "Applications" | "Reports" | "Documents" | "PDF Editor" | "Templates" | "History" | "Converters";

type Props = {
  mode: WorkspaceMode;
  onModeChange: (mode: WorkspaceMode) => void;
  onPrompt: (prompt: string, channel: string) => void;
  profile: { name: string; department: string; university: string };
};

const modes: WorkspaceMode[] = ["Communication", "Applications", "Reports", "Documents", "PDF Editor", "Templates", "History", "Converters"];
const applicationTypes = ["Leave Application", "Bonafide Certificate Application", "Fee Concession Application", "Scholarship Application", "Exam Permission Application", "Attendance Shortage Application", "Internship Permission", "Project Extension", "NOC Request", "Recommendation Letter Request", "Other"];
const reportTypes = ["Event Report", "Hackathon Report", "Workshop Report", "Seminar Report", "Industrial Visit Report", "Project Report", "Placement Report", "Department Report", "Meeting Report", "Research Report", "Other"];

export function WorkspaceModePanel({ mode, onModeChange, onPrompt, profile }: Props) {
  const isCommunication = mode === "Communication";
  return <section className="card mb-6">
    <div className="mb-3 flex items-center gap-2 text-small font-medium text-primary"><FileText className="h-4 w-4" /> WORKSPACE MODE</div>
    <div className="flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Workspace modes">
      {modes.map((item) => <button key={item} type="button" role="tab" aria-selected={mode === item} onClick={() => onModeChange(item)} className={`shrink-0 rounded-lg px-3 py-2 text-small font-medium ${mode === item ? "bg-primary/10 text-primary" : "bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300"}`}>{item}</button>)}
    </div>
    {isCommunication && <p className="mt-3 text-small text-slate-500 dark:text-slate-400">Gmail, Outlook, WhatsApp, SMS, Teams, PDF export, copy, sharing, and your existing communication fields are active below.</p>}
    {mode === "Applications" && <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-small font-medium">Application type<select className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`Create a ${event.target.value} using my profile details. Include recipient, date, reason, request, and signature fields.`, "Formal Application")}><option>{applicationTypes[0]}</option>{applicationTypes.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-small font-medium">Leave / event date<input type="date" className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`Use this date in my application: ${event.target.value}. Do not change other facts.`, "Formal Application")} /></label><label className="text-small font-medium sm:col-span-2">Application details<textarea rows={3} placeholder="Reason, duration, destination, or supporting details" className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(event.target.value, "Formal Application")} /></label><button type="button" onClick={() => onPrompt("Generate an official application using only the facts I provide. Keep missing personal details as placeholders.", "Formal Application")} className="flex items-center justify-center gap-2 rounded-lg bg-primary px-3 py-2 text-small font-medium text-white"><WandSparkles className="h-4 w-4" /> Generate Application</button></div>}
    {mode === "Reports" && <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-small font-medium">Report type<select className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`Create a professional ${event.target.value}.`, "Report")}><option>{reportTypes[0]}</option>{reportTypes.slice(1).map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-small font-medium">Report title<input placeholder="e.g. Annual College Hackathon" className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`Report title: ${event.target.value}`, "Report")} /></label><label className="text-small font-medium">College / department<input defaultValue={profile.university || profile.department} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`College and department: ${event.target.value}`, "Report")} /></label><label className="text-small font-medium">Event date / venue<input placeholder="Only enter known facts" className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(`Event date and venue: ${event.target.value}`, "Report")} /></label><label className="text-small font-medium sm:col-span-2">Report brief<textarea rows={3} placeholder="Objective, activities, participants, results, recommendations" className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 font-normal dark:border-slate-600" onChange={(event) => onPrompt(event.target.value, "Report")} /></label><button type="button" onClick={() => onPrompt("Generate a complete professional report with summary, objectives, main content, results, conclusion, recommendations, references, and signature placeholders. Never invent statistics.", "Report")} className="flex items-center justify-center gap-2 rounded-lg bg-primary px-3 py-2 text-small font-medium text-white"><WandSparkles className="h-4 w-4" /> Generate Report</button></div>}
    {mode === "Converters" && <div className="mt-4 rounded-lg bg-warning/10 p-3 text-small text-slate-600 dark:text-slate-300"><p className="font-semibold">Document conversion requires server-side parsers.</p><p className="mt-1">The current project supports PDF generation and preview. PDF to DOCX, XLSX, PPTX, OCR, and compression are not enabled yet, so no file extension will be changed without a real converter.</p></div>}
    {!["Communication", "Applications", "Reports", "Converters"].includes(mode) && <p className="mt-3 text-small text-slate-500 dark:text-slate-400">Use the Upload My Format panel below to activate this workspace. Original files remain protected and generated output stays editable before export.</p>}
  </section>;
}