"use client";

import Link from "next/link";
import { useState } from "react";
import { Activity, ArrowRight, BarChart3, BriefcaseBusiness, CheckCircle2, ClipboardList, Clock3, FilePlus2, Filter, Settings, ShieldCheck, Target, Users, XCircle } from "lucide-react";

type Job = { id: string; title: string; description: string; location: string | null; jobType: string | null; salaryRange: string | null; requiredSkills: string[]; minCgpa: number | null; applicationDeadline: string | Date | null; isActive: boolean; createdAt: string | Date; _count: { applications: number } };
type Application = { id: string; status: string; appliedAt: string | Date; student: { id: string; name: string; university: string | null; cgpa: number | null; placementProfile: { skills: string[]; resumeScore: number | null } | null }; job: { id: string; title: string } };
type OrganizationData = { organization: { id: string; companyName: string; description: string | null; website: string | null; industry: string | null; verified: boolean } | null; jobs: Job[]; applications: Application[]; notifications: { id: string; title: string; message: string; isRead: boolean; createdAt: string | Date }[]; metrics: { totalJobs: number; activeJobs: number; totalApplications: number; shortlisted: number; interviews: number; selected: number } };

const links = [["Dashboard", "/organization", BarChart3], ["Company Profile", "/organization/profile", ShieldCheck], ["Jobs", "/organization/jobs", BriefcaseBusiness], ["Applicants", "/organization/applicants", Users], ["Shortlisted", "/organization/shortlisted", CheckCircle2], ["Aptitude Tests", "/organization/aptitude", Target], ["Interviews", "/organization/interviews", Clock3], ["Recruitment Pipeline", "/organization/pipeline", Activity], ["Analytics", "/organization/analytics", BarChart3], ["Notifications", "/organization/notifications", ClipboardList], ["Settings", "/organization/settings", Settings]] as const;

function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number }) { return <div className="card"><Icon className="mb-3 h-5 w-5 text-primary" /><p className="text-2xl font-bold">{value}</p><p className="text-small text-slate-500 dark:text-slate-400">{label}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="card py-10 text-center text-small text-slate-500 dark:text-slate-400"><ClipboardList className="mx-auto mb-3 h-8 w-8 text-slate-300" />{text}</div>; }
function statusText(status: string) { return status.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase()); }

export function OrganizationClient({ data, view }: { data: OrganizationData; view: string }) {
    const [applications, setApplications] = useState(data.applications);
    const [jobs, setJobs] = useState(data.jobs);
    const [search, setSearch] = useState("");
    const [status, setStatus] = useState("ALL");
    const [form, setForm] = useState({ title: "", description: "", location: "", jobType: "Full-time", salaryRange: "", requiredSkills: "", minCgpa: "" });
    const [message, setMessage] = useState("");

    const updateApplication = async (applicationId: string, nextStatus: string) => {
        const response = await fetch("/api/organization/application", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ applicationId, status: nextStatus }) });
        if (!response.ok) { setMessage("Unable to update this application."); return; }
        setApplications((items) => items.map((item) => item.id === applicationId ? { ...item, status: nextStatus } : item));
    };
    const createJob = async (event: React.FormEvent) => {
        event.preventDefault(); setMessage("");
        const response = await fetch("/api/organization/job", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, requiredSkills: form.requiredSkills.split(",").map((item) => item.trim()).filter(Boolean), minCgpa: form.minCgpa ? Number(form.minCgpa) : null }) });
        const payload = await response.json();
        if (!response.ok) { setMessage(payload.error ?? "Unable to create job."); return; }
        setJobs((items) => [{ ...payload.job, _count: { applications: 0 } }, ...items]); setMessage("Job created successfully.");
    };

    const filteredApplications = applications.filter((item) => (status === "ALL" || item.status === status) && [item.student.name, item.job.title, ...(item.student.placementProfile?.skills ?? [])].join(" ").toLowerCase().includes(search.toLowerCase()));
    const pageTitle = view === "dashboard" ? "Organization Dashboard" : view === "profile" ? "Company Profile" : view === "jobs" ? "Jobs" : view === "create-job" ? "Create Job" : view === "applicants" ? "Applicants" : view === "shortlisted" ? "Shortlisted Candidates" : view === "pipeline" ? "Recruitment Pipeline" : view === "analytics" ? "Analytics" : view === "notifications" ? "Notifications" : view === "settings" ? "Settings" : view === "aptitude" ? "Aptitude Tests" : "Interviews";
    const shortlisted = applications.filter((item) => item.status === "SHORTLISTED");

    return <div className="space-y-6 p-4 sm:p-6 lg:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-small font-medium text-primary">Organization workspace</p><h1 className="text-heading font-semibold">{pageTitle}</h1><p className="mt-1 text-small text-slate-500 dark:text-slate-400">{data.organization?.companyName ?? "Organization"} · {data.organization?.verified ? "Verified" : "Pending verification"}</p></div><Link href="/organization/jobs/create" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-small font-medium text-white"><FilePlus2 className="h-4 w-4" /> Create Job</Link></div><div className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-2 dark:border-slate-700">{links.map(([label, href, Icon]) => <Link key={href} href={href} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-small ${href === `/organization/${view === "dashboard" ? "" : view}` || (view === "create-job" && href === "/organization/jobs") ? "bg-primary/10 font-medium text-primary" : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}><Icon className="h-4 w-4" />{label}</Link>)}</div>{message && <div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-small text-primary">{message}</div>}

        {view === "dashboard" && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-6"><Metric icon={BriefcaseBusiness} label="Total jobs" value={data.metrics.totalJobs} /><Metric icon={CheckCircle2} label="Active jobs" value={data.metrics.activeJobs} /><Metric icon={Users} label="Applications" value={data.metrics.totalApplications} /><Metric icon={Target} label="Shortlisted" value={data.metrics.shortlisted} /><Metric icon={Clock3} label="Interviews" value={data.metrics.interviews} /><Metric icon={ShieldCheck} label="Selected" value={data.metrics.selected} /></div><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section className="card"><div className="flex items-center justify-between"><div><h2 className="text-card-title font-semibold">Recent Applications</h2><p className="text-small text-slate-500">Candidates applying to your roles.</p></div><Link href="/organization/applicants" className="text-small text-primary">View all</Link></div>{applications.length ? <div className="mt-4 space-y-3">{applications.slice(0, 5).map((item) => <ApplicationRow key={item.id} application={item} onUpdate={updateApplication} />)}</div> : <div className="mt-4"><Empty text="No applications received yet." /></div>}</section><section className="card"><h2 className="text-card-title font-semibold">Applications Overview</h2><div className="mt-5 space-y-3">{["APPLIED", "UNDER_REVIEW", "SHORTLISTED", "INTERVIEW", "SELECTED"].map((stage) => { const count = applications.filter((item) => item.status === stage).length; const width = applications.length ? count / applications.length * 100 : 0; return <div key={stage}><div className="flex justify-between text-small"><span>{statusText(stage)}</span><span>{count}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100 dark:bg-slate-700"><div className="h-full rounded-full bg-primary" style={{ width: `${width}%` }} /></div></div> })}</div></section></div></>}

        {view === "profile" && <section className="card max-w-3xl space-y-5"><div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-small text-amber-800">Verification status: {data.organization?.verified ? "Verified" : "Pending verification"}. Only authorized admins can verify an organization.</div><div className="grid gap-4 sm:grid-cols-2"><Info label="Company name" value={data.organization?.companyName} /><Info label="Industry" value={data.organization?.industry} /><Info label="Website" value={data.organization?.website} /><Info label="Description" value={data.organization?.description} /></div></section>}

        {view === "jobs" && <section className="space-y-4">{jobs.length ? jobs.map((job) => <div key={job.id} className="card flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{job.title}</h2><span className={`rounded-full px-2 py-1 text-xs ${job.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{job.isActive ? "Active" : "Closed"}</span></div><p className="mt-1 text-small text-slate-500">{job.location ?? "Location flexible"} · {job.jobType ?? "Role"} · {job._count.applications} applications</p></div><Link href={`/organization/jobs/${job.id}`} className="inline-flex items-center gap-2 text-small font-medium text-primary">View job <ArrowRight className="h-4 w-4" /></Link></div>) : <Empty text="No jobs posted yet." />}</section>}

        {view === "create-job" && <form onSubmit={createJob} className="card max-w-3xl space-y-4"><Field label="Job title" value={form.title} onChange={(value) => setForm({ ...form, title: value })} required /><label className="block text-small font-medium">Description<textarea required minLength={20} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 min-h-32 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 text-small dark:border-slate-600" /></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Location" value={form.location} onChange={(value) => setForm({ ...form, location: value })} required /><Field label="Job type" value={form.jobType} onChange={(value) => setForm({ ...form, jobType: value })} required /><Field label="Salary range" value={form.salaryRange} onChange={(value) => setForm({ ...form, salaryRange: value })} /><Field label="Minimum CGPA" type="number" value={form.minCgpa} onChange={(value) => setForm({ ...form, minCgpa: value })} /></div><Field label="Required skills (comma separated)" value={form.requiredSkills} onChange={(value) => setForm({ ...form, requiredSkills: value })} /><button type="submit" className="rounded-lg bg-primary px-4 py-2 text-small font-medium text-white">Publish Job</button></form>}

        {(view === "applicants" || view === "shortlisted") && <section className="space-y-4"><div className="card flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2"><Filter className="h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search applicants..." className="w-full bg-transparent text-small outline-none" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-small dark:border-slate-700"><option value="ALL">All status</option>{["APPLIED", "UNDER_REVIEW", "SHORTLISTED", "APTITUDE", "INTERVIEW", "SELECTED", "REJECTED"].map((item) => <option key={item} value={item}>{statusText(item)}</option>)}</select></div>{(view === "shortlisted" ? shortlisted : filteredApplications).length ? (view === "shortlisted" ? shortlisted : filteredApplications).map((item) => <ApplicationRow key={item.id} application={item} onUpdate={updateApplication} />) : <Empty text="No applicants found." />}</section>}

        {view === "pipeline" && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{["APPLIED", "UNDER_REVIEW", "SHORTLISTED", "APTITUDE", "INTERVIEW", "SELECTED"].map((stage) => <section key={stage} className="card min-h-48"><div className="flex justify-between"><h2 className="font-semibold">{statusText(stage)}</h2><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{applications.filter((item) => item.status === stage).length}</span></div><div className="mt-4 space-y-2">{applications.filter((item) => item.status === stage).slice(0, 5).map((item) => <div key={item.id} className="rounded-lg border border-slate-200 p-2 text-small dark:border-slate-700">{item.student.name}<p className="text-xs text-slate-500">{item.job.title}</p></div>)}</div></section>)}</div>}

        {view === "analytics" && <div className="grid gap-6 lg:grid-cols-2"><section className="card"><h2 className="text-card-title font-semibold">Hiring funnel</h2><div className="mt-5 space-y-3">{["APPLIED", "SHORTLISTED", "INTERVIEW", "SELECTED"].map((stage) => <div key={stage} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-small dark:bg-slate-800"><span>{statusText(stage)}</span><strong>{applications.filter((item) => item.status === stage).length}</strong></div>)}</div></section><section className="card"><h2 className="text-card-title font-semibold">Job performance</h2>{jobs.length ? <div className="mt-4 space-y-3">{jobs.map((job) => <div key={job.id} className="flex justify-between border-b border-slate-100 pb-3 text-small dark:border-slate-700"><span>{job.title}</span><span>{job._count.applications} applications</span></div>)}</div> : <p className="mt-4 text-small text-slate-500">No job data yet.</p>}</section></div>}

        {view === "notifications" && <section className="space-y-3">{data.notifications.length ? data.notifications.map((item) => <div key={item.id} className="card"><div className="flex items-start gap-3"><ClipboardList className="h-5 w-5 text-primary" /><div><h2 className="font-medium">{item.title}</h2><p className="mt-1 text-small text-slate-500">{item.message}</p><p className="mt-2 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p></div></div></div>) : <Empty text="No organization notifications yet." />}</section>}

        {view === "aptitude" && <Empty text="Organization aptitude assessments are ready to be configured." />}
        {view === "interviews" && <section className="space-y-4"><div className="card rounded-xl border border-amber-200 bg-amber-50 p-4 text-small text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200">Interview scheduling is now active. Schedule interviews directly from shortlisted candidates and track their round status here.</div><div className="card"><h2 className="text-card-title font-semibold">Interview pipeline</h2><p className="mt-1 text-small text-slate-500">Use the dedicated interview scheduling page to manage all interview rounds.</p><div className="mt-4"><Link href="/organization/interviews" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-small font-medium text-white">Open interview dashboard <ArrowRight className="h-4 w-4" /></Link></div></div></section>}
        {view === "settings" && <Empty text="Organization settings are ready to configure." />}
    </div>;
}

function Info({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-small font-medium">{value || "Not provided"}</p></div>; }
function Field({ label, value, onChange, required = false, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <label className="block text-small font-medium">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent px-3 py-2 text-small dark:border-slate-600" /></label>; }
function ApplicationRow({ application, onUpdate }: { application: Application; onUpdate: (id: string, status: string) => void }) { return <div className="card flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h3 className="font-medium">{application.student.name}</h3><p className="text-small text-slate-500">{application.job.title} · {application.student.university || "University not provided"} · CGPA {application.student.cgpa ?? "N/A"}</p><p className="mt-1 text-xs text-slate-500">Skills: {application.student.placementProfile?.skills.join(", ") || "Not provided"}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{statusText(application.status)}</span><select value={application.status} onChange={(event) => onUpdate(application.id, event.target.value)} className="rounded-lg border border-slate-200 bg-transparent px-2 py-2 text-xs dark:border-slate-700"><option value="APPLIED">Applied</option><option value="UNDER_REVIEW">Under review</option><option value="SHORTLISTED">Shortlisted</option><option value="APTITUDE">Aptitude</option><option value="INTERVIEW">Interview</option><option value="SELECTED">Selected</option><option value="REJECTED">Rejected</option></select></div>; }
