import Link from "next/link";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const params = await searchParams;
  const query = params.q?.trim() || "";
  const page = Math.max(1, Number(params.page) || 1);
  const pageSize = 20;
  const where = { role: "STUDENT" as const, ...(query ? { OR: [{ name: { contains: query, mode: "insensitive" as const } }, { email: { contains: query, mode: "insensitive" as const } }] } : {}) };
  const [users, total] = await Promise.all([prisma.user.findMany({ where, select: { id: true, name: true, email: true, university: true, createdAt: true, updatedAt: true, _count: { select: { courses: true, assignments: true, exams: true, studyPlans: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), prisma.user.count({ where })]);
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <section className="p-6 lg:p-8"><div className="mb-8"><p className="text-sm font-medium text-primary">Students</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">All students</h1><p className="mt-2 text-sm text-slate-500">{total} students from the live application database.</p></div><form className="mb-4 flex max-w-xl gap-2" method="get"><label className="sr-only" htmlFor="student-search">Search students</label><input id="student-search" name="q" defaultValue={query} placeholder="Search by name or email" className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary dark:border-slate-700 dark:bg-slate-900" /><button className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white" type="submit">Search</button></form><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{users.length === 0 ? <p className="p-6 text-sm text-slate-500">No students found.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Academic records</th><th className="px-5 py-3">Last activity</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{users.map(user => <tr key={user.id}><td className="px-5 py-4"><p className="font-medium">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">STUDENT</span></td><td className="px-5 py-4 text-slate-500">{user._count.courses} courses · {user._count.assignments} assignments · {user._count.exams} exams · {user._count.studyPlans} plans</td><td className="px-5 py-4 text-slate-500">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(user.updatedAt)}</td><td className="px-5 py-4 text-slate-500">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(user.createdAt)}</td><td className="px-5 py-4"><Link href={`/admin/users/${user.id}`} className="font-medium text-primary hover:underline">View profile</Link></td></tr>)}</tbody></table></div>}<div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 text-sm dark:border-slate-800"><span className="text-slate-500">Page {page} of {pages}</span><div className="flex gap-3">{page > 1 && <Link className="text-primary" href={`/admin/users?q=${encodeURIComponent(query)}&page=${page - 1}`}>Previous</Link>}{page < pages && <Link className="text-primary" href={`/admin/users?q=${encodeURIComponent(query)}&page=${page + 1}`}>Next</Link>}</div></div></div></section>;
}
