ALTER TABLE "PlacementJob"
  ADD COLUMN IF NOT EXISTS "recruitmentTitle" TEXT,
  ADD COLUMN IF NOT EXISTS "jobCode" TEXT,
  ADD COLUMN IF NOT EXISTS "department" TEXT,
  ADD COLUMN IF NOT EXISTS "jobSummary" TEXT,
  ADD COLUMN IF NOT EXISTS "preferredSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "employmentType" TEXT,
  ADD COLUMN IF NOT EXISTS "workMode" TEXT,
  ADD COLUMN IF NOT EXISTS "maxCgpa" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "openings" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "applicationStartDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "expectedJoiningDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "eligibility" JSONB,
  ADD COLUMN IF NOT EXISTS "benefits" JSONB,
  ADD COLUMN IF NOT EXISTS "recruitmentRounds" JSONB,
  ADD COLUMN IF NOT EXISTS "applicationForm" JSONB,
  ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PUBLISHED';

ALTER TABLE "PlacementApplication"
  ADD COLUMN IF NOT EXISTS "formData" JSONB;

CREATE INDEX IF NOT EXISTS "PlacementJob_status_idx" ON "PlacementJob"("status");
