"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, GripVertical, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { presentationSchema, type PresentationDocument } from "@/lib/ppt";

export function PptPlan({ presentationId, document: initial }: { presentationId: string; document: unknown }) {
  const parsed = presentationSchema.safeParse(initial);
  const [document, setDocument] = useState<PresentationDocument>(parsed.success ? parsed.data : { title: "Presentation", subtitle: "", theme: "modern", slides: [] });
  function remove(id: string) { setDocument((current) => ({ ...current, slides: current.slides.filter((slide) => slide.id !== id) })); }
  function add() { setDocument((current) => ({ ...current, slides: [...current.slides, { id: `slide-${Date.now()}`, title: "New slide", description: "Add a description in the editor.", layout: "title-content", visualType: "content", background: "#f7f9fc", notes: "", elements: [] }] })); }
  return <main className="min-h-screen bg-[#f5f7fb] px-4 py-8 dark:bg-slate-950"><div className="mx-auto max-w-5xl"><Link href="/ai-tools/ppt-generator" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft className="h-4 w-4" />Back to generator</Link><div className="mt-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-cyan-700">AI presentation plan</p><h1 className="mt-1 text-3xl font-semibold">{document.title}</h1><p className="mt-2 text-sm text-slate-500">{document.slides.length} slides · {document.subtitle} · {document.theme}</p></div><div className="flex gap-2"><button onClick={add} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium dark:border-slate-700 dark:bg-slate-900"><Plus className="h-4 w-4" />Add slide</button><Link href={`/ai-tools/ppt-generator/editor/${presentationId}`} className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-cyan-400 dark:text-slate-950">Continue to editor<ArrowRight className="h-4 w-4" /></Link></div></div><div className="mt-8 space-y-3">{document.slides.map((slide, index) => <article key={slide.id} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><GripVertical className="h-5 w-5 text-slate-300" /><div className="flex h-16 w-24 shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 text-xs font-semibold dark:border-slate-700 dark:bg-slate-800">{String(index + 1).padStart(2, "0")}</div><div className="min-w-0 flex-1"><p className="text-xs font-medium text-cyan-700">Slide {String(index + 1).padStart(2, "0")} · {slide.layout}</p><h2 className="mt-1 truncate font-semibold">{slide.title}</h2><p className="mt-1 truncate text-sm text-slate-500">{slide.description}</p></div><button onClick={() => remove(slide.id)} title="Delete slide" aria-label="Delete slide" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></article>)}</div></div></main>;
}
